# Generated by Django 6.0 on 2025-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('party', 'Party'), ('formal', 'Formal')], max_length=10)),
                ('style', models.CharField(choices=[('street', 'Street'), ('traditional', 'Traditional'), ('minimal', 'Minimal')], max_length=15)),
                ('color', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='outfits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
